Controllers/EmployeeAttendanceController.cs
using EmployeeAttendenceMangement.AMSConnecction;
using EmployeeAttendenceMangement.Models;
using PagedList;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace EmployeeAttendenceMangement.Controllers
{
    public class EmployeeAttendanceController : Controller
    {
        public ActionResult EmployeeAttandenceDetail(int? page, int? pageSize)
        {
            EmployeeAttandenceDateLayer EmpAttandence_layer = new EmployeeAttandenceDateLayer();           
            int pageIndex = 1;
            pageIndex = page.HasValue ? Convert.ToInt32(page) : 1;
            int defaSize = (pageSize ?? 10);
            ViewBag.psize = defaSize;
            ModelState.Clear();
            return View(EmpAttandence_layer.GetMarkAttandence(Convert.ToBoolean(Session["Is_admin"]), Convert.ToInt32(Session["EmployeeId"])).ToList().ToPagedList(pageIndex, defaSize));
        }
        
        public ActionResult CreateAttandence()
        {      
                return View();            
        }

        [HttpPost]
        public ActionResult CreateAttandence(EmployeeAttandenceModel model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    EmployeeAttandenceDateLayer EmpAttandence_layer = new EmployeeAttandenceDateLayer();

                    if (EmpAttandence_layer.createAttandence(model))
                    {
                        ViewBag.Message = "Employee details added successfully";

                        Session["Date"] = model.Date.ToString();
                        
                        Session["EmployeeId"] = model.EmployeeId.ToString();
                        return Redirect("EmployeeAttandenceDetail");
                    }

                }

                return View();
            }
            catch(Exception er)
            {
                return View();
            }
        }


        public ActionResult UpdateAttendance(int EmpAtendenceId)
        {
            EmployeeAttandenceDateLayer EmpAttandence_layer = new EmployeeAttandenceDateLayer();
            EmployeeAttandenceModel model = new EmployeeAttandenceModel();
            int EmpAttendance = EmpAttandence_layer.GetEmployeeId(EmpAtendenceId,model);
           
            Session["AltlastName"] = model.LastName;
            Session["AltEmployeeId"] = model.EmployeeId;
            Session["AltFirstName"] = model.FirstName;
            var outtime = model.OutTime;


            var Data1 = outtime.ToString().Substring(0, 5);
            if (Data1 == "00:00" )
           {
                Session["Outtime"] = null;

           }
            else
            {
                Session["Outtime"] = model.OutTime.ToString().Substring(0, 5);
                 
            }


            return View(EmpAttandence_layer.GetMarkAttandence().Find(Emp => Emp.EmpAtendenceId == EmpAtendenceId));
        }

        
        [HttpPost]
        public ActionResult UpdateAttendance(EmployeeAttandenceModel obj)
        {
            try
            {
                EmployeeAttandenceDateLayer EmpAttandence_layer = new EmployeeAttandenceDateLayer();

                EmpAttandence_layer.UpdateEmployeeAttandence(obj);
                return Redirect("EmployeeAttandenceDetail");
            }
            catch (Exception er)
            {
                return View();
            }
        }
        public string CreateBtnHide()
        {
            EmployeeAttandenceDateLayer EmpAttandence_layer = new EmployeeAttandenceDateLayer();

            if (EmpAttandence_layer.CreateBtnHide(Convert.ToInt32(Session["EmployeeId"])))
            {
                return "1";
            }
            else
            {
                return "0";
            }

        }
        public ActionResult EmpAttendanceDelete(String EmpAtendenceId)
        {
            try
            {
                EmployeeAttandenceDateLayer EmpAttandence_layer = new EmployeeAttandenceDateLayer();
                int result = EmpAttandence_layer.DeleteData(EmpAtendenceId);
                TempData["result3"] = result;
                ModelState.Clear();
                return RedirectToAction("EmployeeAttandenceDetail");
            }
            catch(Exception er)
            {
                return View();
            }
        }
    }
}

Controllers/EmployeeController.cs
using DocumentFormat.OpenXml.Office.CustomXsn;
using EmployeeAttendenceMangement.AMSConnecction;
using EmployeeAttendenceMangement.Models;
using PagedList;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data;
using System.Data.SqlClient;
using System.Linq;
using System.Security.Cryptography;
using System.Text;
using System.Web;
using System.Web.Mvc;

namespace EmployeeAttendenceMangement.Controllers
{
    public class EmployeeController : Controller
    {
        AMS_Access_Layer access_Layer = new AMS_Access_Layer();

        public ActionResult EmployeeDetail(int? page, int? pageSize)
        {
            AMS_Access_Layer access_Layer = new AMS_Access_Layer();
            int pageIndex = 1;
            pageIndex = page.HasValue ? Convert.ToInt32(page) : 1;
            int defaSize = (pageSize ?? 10);
            ViewBag.psize = defaSize;
            ModelState.Clear();
            
            return View(access_Layer.GetEmployee(Convert.ToBoolean(Session["Is_admin"]), Convert.ToInt32(Session["EmployeeId"])).ToList().ToPagedList(pageIndex, defaSize));
        }

        //public ActionResult ValidatealtEmailId1()
        //{
        //    EmployeeCreateModel model = new EmployeeCreateModel();
        //    AMS_Access_Layer access_Layer = new AMS_Access_Layer();
        //    ViewBag.ValidateEmailId1 = access_Layer.ValidateEmailId1();           
        //    return View(access_Layer.ValidateEmailId1());
        //}


        public int ValidateEmailId(String EmailId)
        {
            var EmailIdData  = access_Layer.ValidateEmailId(EmailId);
            if (EmailIdData == 0)
            {
                return 0;
            }
            else
            {
                return 1;
            }
            
        }
       
        public ActionResult Create()
        {
            ViewBag.CountryList = CountryList();
         
            EmployeeCreateModel model = new EmployeeCreateModel();
            var maxId = access_Layer.GetEmployeeId(model);

            if (maxId == "0")
            {
                model.EmployeeId = Convert.ToInt32(DateTime.Now.Year.ToString() + "" + "000" + "" + (1).ToString());
            }
            else
            {
                model.EmployeeId = model.EmployeeId + 1;
            }
            
            if (Convert.ToBoolean(Session["Is_admin"]) == true)
            {
                return View(model);
            }

            return Redirect("EmployeeDetail");
        }
        private static List<Country> CountryList()
        {
            List<Country> countries = new List<Country>();
            string constr = ConfigurationManager.ConnectionStrings["AttendanceManagementConn"].ConnectionString;
            using (SqlConnection con = new SqlConnection(constr))
            {
                string query = "select * from Country";
                using (SqlCommand cmd = new SqlCommand(query))
                {
                    cmd.Connection = con;

                    con.Open();
                    using (SqlDataReader sdr = cmd.ExecuteReader())
                    {
                        while (sdr.Read())
                        {
                            countries.Add(new Country
                            {
                                CountryName = sdr["CountryName"].ToString(),
                                CountryId = Convert.ToInt32(sdr["CountryId"])
                            });
                        }
                    }
                    con.Close();
                }
            }

            return countries;
        }

        public JsonResult State_Bind(int CountryId)
        {

            DataSet ds = access_Layer.Get_State(CountryId);
            List<SelectListItem> statelist = new List<SelectListItem>();
            foreach (DataRow dr in ds.Tables[0].Rows)
            {
                statelist.Add(new SelectListItem { Text = dr["StateName"].ToString(), Value = dr["StateId"].ToString() });
            }
            return Json(statelist, JsonRequestBehavior.AllowGet);

        }

        public ActionResult Delete(String EmployeeId)   
        {

            try
            {
                AMS_Access_Layer access_Layer = new AMS_Access_Layer();
                int result = access_Layer.DeleteData(EmployeeId);
                TempData["result3"] = result;
                ModelState.Clear();
                return RedirectToAction("EmployeeDetail");
            }
            catch (Exception er)
            {
                return View();
            }
        }
     
        [HttpPost]
        public ActionResult Create(EmployeeCreateModel model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    AMS_Access_Layer access_Layer = new AMS_Access_Layer();

                 var date1= access_Layer.ValidatealtEmailId(Convert.ToString(model.AlternateEmailId));
                 var ChkEmail = access_Layer.ValidateEmailId(Convert.ToString(model.AlternateEmailId));


                    if (model.AlternateEmailId == model.EmailId)
                    {
                        TempData["AltEmailmsg"] = "Primary EmailId  and Alternate EmailId should not be same,Type again !";


                        if (ChkEmail == 1)
                        {

                            TempData["EmailValidation"] = "EmailId all ready registered";
                        }
                        ViewBag.CountryList = CountryList();
                        ViewBag.CountryList1 = GetStateByEmp(Convert.ToInt32(model.CountryId));
                        return View(model);
                    }
                    

                    if (access_Layer.AddEmployee(model))
                    {
                        ViewBag.Message = "Employee details added successfully";
                        return RedirectToAction("EmployeeDetail");
                    }
                }
                ViewBag.CountryList =CountryList();
                ViewBag.CountryList1 = GetStateByEmp(Convert.ToInt32(model.CountryId));
                TempData["EmailValidation"] = "EmailId all ready registered";

                return View(model);
            }
            catch (Exception er)
            {
                return View();
            }
        }

        private static List<State> GetStateByEmp(int countryid)
        {
            List<State> states = new List<State>();
            string constr = ConfigurationManager.ConnectionStrings["AttendanceManagementConn"].ConnectionString;
            using (SqlConnection con = new SqlConnection(constr))
            {
                string query = "select * from State where CountryId ="+countryid+" ";
                using (SqlCommand cmd = new SqlCommand(query))
                {
                    cmd.Connection = con;

                    con.Open();
                    using (SqlDataReader sdr = cmd.ExecuteReader())
                    {
                        while (sdr.Read())
                        {
                            states.Add(new State
                            {
                                StateName = sdr["StateName"].ToString(),
                                StateId = Convert.ToInt32(sdr["StateId"])
                            });
                        }
                    }
                    con.Close();
                }
            }

            return states;
        }
        public ActionResult Edit(int EmployeeId)
        {
            AMS_Access_Layer access_Layer = new AMS_Access_Layer();
            int StateByEmpId = access_Layer.Get_StateByEmpId(EmployeeId);
            ViewBag.CountryList = CountryList();
            ViewBag.CountryList1 = GetStateByEmp(StateByEmpId);
            return View(access_Layer.GetEmployee().Find(EmployeeCreateModel => EmployeeCreateModel.EmployeeId == EmployeeId));
        }

        [HttpPost]
        public ActionResult Edit(EmployeeCreateModel obj,int EmployeeId)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    AMS_Access_Layer access_Layer = new AMS_Access_Layer();
                    if (access_Layer.UpdateEmployee(obj))
                    {
                        return RedirectToAction("EmployeeDetail");
                    }
                }
                int StateByEmpId = access_Layer.Get_StateByEmpId(EmployeeId);
                ViewBag.CountryList = CountryList();
                ViewBag.CountryList1 = GetStateByEmp(StateByEmpId);
                return View();
            }

            catch (Exception er)
            {
                return View();
            }
        }


        public ActionResult Login()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Login(EmployeeCreateModel model)
        {
            try
            {
                if(ModelState.IsValid)
                {
                    AMS_Access_Layer access_Layer = new AMS_Access_Layer();

                    if (access_Layer.GetLogin(model))
                    { 
                        Session["FirstName"] = model.FirstName;
                        Session["Is_admin"] = model.Is_admin;
                        Session["LastName"] = model.LastName;                       
                        Session["EmployeeId"] = model.EmployeeId;
                     

                        ViewBag.Message = "Employee details added successfully";
                        return RedirectToAction("Index", "Home");
                    }
                }
                if (model.FirstName != null)
                {
                    TempData["msg2"] = " Invalid Password  Retry !!";
                }
                else
                {
                    TempData["msg1"] = "No account found for this email. Retry !!";
                }

                return View();
            }

Controllers/ProjectMasterController.cs
using EmployeeAttendenceMangement.AMSConnecction;
using EmployeeAttendenceMangement.Models;
using PagedList;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace EmployeeAttendenceMangement.Controllers
{

  
    public class ProjectMasterController : Controller
    {

        ProjectDataLayer Project_Layer = new ProjectDataLayer();
     
        public ActionResult ProjectDetail(int? page, int? pageSize)
        {
            ProjectDataLayer Project_Layer = new ProjectDataLayer();

            int pageIndex = 1;
            pageIndex = page.HasValue ? Convert.ToInt32(page) : 1;
            int defaSize = (pageSize ?? 5);
            ViewBag.psize = defaSize;
            ModelState.Clear();

            return View(Project_Layer.GetProjectMaster().ToList().ToPagedList(pageIndex, defaSize));
        }

     
        // GET: ProjectMaster/Create
        public ActionResult CreateProject()
        {
            return View();
        }

       
        [HttpPost]
        public ActionResult CreateProject(ProjectMasterModel model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    ProjectDataLayer Project_Layer = new ProjectDataLayer();

                    if (Project_Layer.AddProject(model))
                    {
                        ViewBag.Message = "Employee details added successfully";
                    }
                }

                return Redirect("ProjectDetail");
            }
            catch(Exception er)
            {
                return View();
            }
        }


        public ActionResult UpdateProject(int ProjectId)
        {
            ProjectDataLayer Project_Layer = new ProjectDataLayer();

            return View(Project_Layer.GetProjectMaster().Find(Emp => Emp.ProjectId == ProjectId));
        }

        // POST: ProjectMaster/Edit/5
        [HttpPost]
        public ActionResult UpdateProject( ProjectMasterModel model)
        {
            try
            {
                ProjectDataLayer Project_Layer = new ProjectDataLayer();

                Project_Layer.UpdateProjectMaster(model);
                return RedirectToAction("Index","Home");
            }
            catch(Exception er)
            {
                return View();
            }
        }

        // GET: ProjectMaster/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: ProjectMaster/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Attendance Management System.</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1.0" name="viewport">

    <title>Employee Management System</title>
    <meta content="" name="description">
    <meta content="" name="keywords">

    <!-- Favicons -->
    <link href="~/assets/img/favicon.png" rel="icon">
    <link href="~/assetsimg/apple-touch-icon.png" rel="apple-touch-icon">

    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Raleway:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

    <!-- Vendor CSS Files -->
    <link href="~/assets/vendor/animate.css/animate.css" rel="stylesheet" />
    <link href="~/assets/vendor/animate.css/animate.min.css" rel="stylesheet">
    <link href="~/assets/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link href="~/assets/vendor/bootstrap-icons/bootstrap-icons.css" rel="stylesheet">
    <link href="~/assets/vendor/boxicons/css/boxicons.min.css" rel="stylesheet">
    <link href="~/assets/vendor/glightbox/css/glightbox.min.css" rel="stylesheet">
    <link href="~/assets/vendor/swiper/swiper-bundle.min.css" rel="stylesheet">


    <!-- Template Main CSS File -->
    <link href="~/assets/css/style.css" rel="stylesheet" />


    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Scripts/bootstrap-dtpicker.min.css" rel="stylesheet" />
    <script src="~/Scripts/bootstrap.min.js"></script>
    <style>
        hmtl
        {
            height: 100%;
        }

        body
        {
          
            position: relative;
            margin: 0px;
            min-height: 100px;
            padding-bottom: 6.74rem;
            box-sizing: inherit
        }

        h5 {
            color: white;
            margin-top: 18px;
        }

        p {
        
            text-align: center;

            padding-top: 15px;
        }
       
        footer {
            position: fixed;
            bottom: 0px;
            left: 0px;
            right: 0px;
            text-align: center;
            background-color: #ccd8ff;
            height: 50px;
        }

        .pagination > .active > a, .pagination > .active > a:focus, .pagination > .active > a:hover, .pagination > .active > span, .pagination > .active > span:focus, .pagination > .active > span:hover {
            z-index: 0;
        }
    </style>

</head>
<body>

    <header id="header" class="d-flex align-items-center navbar-fixed-top">
        <div class="container d-flex justify-content-between align-items-center">

            <div class="logo">
                <h1>@Html.ActionLink("E Management System", "Index", "Home")</h1>
                <a href="index.html"><img src="~/assetsimg/logo.png" alt="" class="img-fluid"></a>
            </div>

            <nav id="navbar" class="navbar">
                <ul >
                    <li style="color: white; margin-top: 18px; " class="glyphicon glyphicon-home"> </li>
                    <li> @Html.ActionLink("Home", "Index", "Home")</li>

                    @if (Session["FirstName"] != null)
                    {
                        <li>@Html.ActionLink("Employee Detail", "EmployeeDetail", "Employee")</li>
                    }
                    else
                    {
                        <li>@Html.ActionLink("Employee Detail", "Index", "Home")</li>
                    }
                    @if (Convert.ToBoolean(Session["Is_admin"]) == true)
                    {
                        <li>@Html.ActionLink("Project", "ProjectDetail", "ProjectMaster")</li>
                    }
                    else
                    {

                    }
                    @if (Convert.ToBoolean(Session["Is_admin"]) == true)
                    {
                        <li>@Html.ActionLink("Project Mapping", "Project_EmployeeMapping", "EmployeeProjectMapping")</li>
                    }
                    else
                    {


                    }
                    @if (Session["FirstName"] != null)
                    {
                        <li>@Html.ActionLink("Attendance Detail", "EmployeeAttandenceDetail", "EmployeeAttendance")</li>
                    }
                    else
                    {
                        <li>@Html.ActionLink("Attendance Detail", "Index", "Home")</li>

                    }
                </ul>

                <ul class="navbar-right">

                    @if (Session["EmployeeId"] != null)
                    {
                        <li class="btn-btn-primary"><h5>@Session["FirstName"]</h5></li>
                        <li>@Html.ActionLink("LogOut", "LogOut", "Employee")</li>
                    }
                    else
                    {
                        <li><span style="color: white; margin-top: 18px; " class="glyphicon glyphicon-user"></span></li>
                        <li>@Html.ActionLink("Login", "Login", "Employee")</li>
                    }
                   
                </ul>
            </nav> 

        </div>
    </header>

    <div class="container body-content">
        @RenderBody()

        <footer>

            <p style="text-align: center">Copyright &copy; | info@betaedge.in </p>


        </footer>

    </div>

    <script src="~/Scripts/jquery-3.4.1.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    <link href="~/Scripts/bootstrap-dtpicker.min.css" rel="stylesheet" />

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)

</body>
</html>