Models/EmployeeProjectMapping.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace EmployeeAttendenceMangement.Models
{
    public class EmployeeProjectMapping
    {
        public int Emp_Project_Mapping_Id { get; set; }
 
        public Nullable<int> Project_Id { get; set; }

    
        public Nullable<int> Employee_Id { get; set; }

        public virtual EmployeeCreateModel Employee { get; set; }

        public string ProjectName { get; set; }
        public string FirstName { get; set; }
        public virtual ProjectMasterModel ProjectMasterModel { get; set; }
    }
}

Controllers/EmployeeProjectMappingController.cs
using EmployeeAttendenceMangement.AMSConnecction;
using EmployeeAttendenceMangement.Models;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data;
using System.Data.SqlClient;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace EmployeeAttendenceMangement.Controllers
{
    public class EmployeeProjectMappingController : Controller
    {
        EmployeeProjectMapping_layer projectDataLayer = new EmployeeProjectMapping_layer();
        public ActionResult Project_EmployeeMapping()
        {

            ViewBag.ProjectLists = ProjectList();
            return View();
        }
        [HttpPost]
        public ActionResult Project_EmployeeMapping(EmployeeProjectMapping model)
        {
            try
            {
              
                    if (projectDataLayer.AddEmployeeProject(model))
                    {
                        ViewBag.Message = "Employee details added successfully";
                    }
                         
                return RedirectToAction("Index","Home", new { area = "" }); 
            }
            catch(Exception er)
            {
                return View();
            }
        }

        private static List<EmployeeProjectMapping> ProjectList()
        {
            List<EmployeeProjectMapping> Projects = new List<EmployeeProjectMapping>();
            string constr = ConfigurationManager.ConnectionStrings["AttendanceManagementConn"].ConnectionString;
            using (SqlConnection con = new SqlConnection(constr))
            {
                string query = "select * from Project_Master";
                using (SqlCommand cmd = new SqlCommand(query))
                {
                    cmd.Connection = con;

                    con.Open();
                    using (SqlDataReader sdr = cmd.ExecuteReader())
                    {
                        while (sdr.Read())
                        {
                            Projects.Add(new EmployeeProjectMapping
                            {
                            ProjectName   = sdr["ProjectName"].ToString(),
                                Project_Id = Convert.ToInt32(sdr["ProjectId"])
                            });
                        }
                    }
                    con.Close();
                }
            }

            return Projects;
        }

        public JsonResult GetEmployeeName(int ProjectCode)
        {
            DataSet ds = projectDataLayer.Get_EmployeeName(ProjectCode);
            List<SelectListItem> statelist = new List<SelectListItem>();
            foreach (DataRow dr in ds.Tables[0].Rows)
            {
                statelist.Add(new SelectListItem { Text = dr["FirstName"].ToString(), Value = dr["EmployeeId"].ToString() });
            }
            return Json(statelist, JsonRequestBehavior.AllowGet);
        }

 



    }
}

Views/EmployeeProjectMapping/Project_EmployeeMapping.cshtml
@model EmployeeAttendenceMangement.Models.EmployeeProjectMapping

<div class="header">


    <h1>Project Employee Mapping </h1>
    

</div>
<style>
    form {
     margin-top:60px;
        margin-left:230px;
        margin-right:230px;
        box-shadow: 2px 6px 50px gray;
        border-radius: 10px 40px;
        border: 1px solid black;
        padding-top: 10px;
        padding-Right:230px;
    }

    .txt_right {
        margin-left: 20px;
    }

    .main-container {
        height: auto;
        margin-top: 10px;
    }

    .zoom:hover {
        -ms-transform: scale(1.1); /* IE 9 */
        -webkit-transform: scale(1); /* Safari 3-8 */
        transform: scale(1.1);
        transition: 0.5s;
    }

    #text {
        float: left;
        width: 100px;
    }


    select {
        width: 200px;
        height: 29px;
        border-radius: 3px;
        border: 1px solid #CCC;
        font-weight: 200;
        font-size: 15px;
        font-family: Verdana;
        box-shadow: 1px 1px 5px #CCC;
    }

        select: hover {
            width: 200px;
            height: 29px;
            border-radius: 3px;
            border: 1px solid #CCC;
            font-weight: 200;
            font-size: 15px;
            font-family: Verdana;
            box-shadow: 1px 1px 5px #CCC;
        }

    .reg {
        margin-left: 40px;
    }
</style>


<style>
    div.header {
        background-color: black;
        padding-bottom:10px;

    }

    body {
        background-color: #fcfafa;
    }

    .form-horizontal {
        overflow: hidden;
    }

    h1 {
        color: white;
        text-align: center;
        margin-top: 18px;
    }
</style>
@using (Html.BeginForm("Project_EmployeeMapping", "EmployeeProjectMapping", FormMethod.Post))
{
    <br />
    <br />

    @Html.AntiForgeryToken()

    <div class="form-horizontal">

        @Html.ValidationSummary(true, "ModelOnly", new { @class = "text-danger" })
        <div class="form-group">
            @Html.HiddenFor(model => model.Emp_Project_Mapping_Id)
            @Html.Label("Project Name", htmlAttributes: new { @class = "control-label col-md-4" })
            <div class="col-md-offset-4">

                @Html.DropDownList("Project_Id", new SelectList(ViewBag.ProjectLists, "Project_Id", "ProjectName"), "---Select Project Name---", htmlAttributes: new { @class = "form-control", @style = "width:460px ;height:45px;", Id = "Pid", required = "required" })

                @Html.ValidationMessageFor(model => model.Project_Id, "", new { @class = "text-danger" })

            </div>

        </div>
        <div class="form-group">
            @Html.Label("Employee Name", htmlAttributes: new { @class = "control-label col-md-4" })
            <div class="col-md-offset-4">

                @Html.DropDownListFor(model => model.Employee_Id, new SelectList(""), " ---Select Employee Name ---", htmlAttributes: new { @class = "form-control", @style = "width:460px; ;height:45px;", Id = "EmpId", required = "required" })


                @*@Html.DropDownListFor(model => model.Employee_Id, new SelectList(ViewBag.CountryList1, "StateId", "StateName"), "---Select State Name ---", htmlAttributes: new { @class = "form-control", @style = "width:260px", Id = "St", required = "required" })*@


                @Html.ValidationMessageFor(model => model.Employee_Id, "", new { @class = "text-danger" })

            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-6 col-md-10">
                <input type="submit" value="save" class="btn btn-success" />
            </div>
        </div>
    </div>
}


<script type="text/javascript">
    $(function () {
        $("#Pid").change(function () {
            var id = $(this).val();
            debugger;
            $("#EmpId").empty();
            $.get("/EmployeeProjectMapping/GetEmployeeName", { ProjectCode: $("#Pid").val() }, function (data) {
                debugger;
                var v = "<option>---Select---</option>";
                $.each(data, function (i, v1) {
                    v += "<option value=" + v1.Value + ">" + v1.Text + "</option>";


                });
                $("#EmpId").html(v);
            })
        });

    });
</script>